### ISSUE TITLE
support returning multiple records from VRL function

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1074]
### Which OpenObserve functionalities are relevant/related to the feature request?

functions

### Description

Currently functions takes 1 record as input and return 1 or 0 records as output. For a scenario where you have an array in the source and want multiple records it won't work.

e.g.

```json
{
  "Records": [
    {
      "eventVersion": "1.08",
      "userIdentity": {
        "accountId": "123243534"
      },
      "eventTime": "2022-09-28T06:41:11Z",
      "eventSource": "lakeformation.amazonaws.com",
      "requestID": "249f1ffd-613a-4c3d-a720-ed133ab5cc8c",
      "eventType": "AwsApiCall",
      "managementEvent": true,
      "eventCategory": "Management"
    },
    {
      "eventVersion": "1.08",
      "userIdentity": {
        "accountId": "123243534"
      },
      "eventTime": "2022-09-28T06:42:11Z",
      "eventSource": "cloudwatch.amazonaws.com",
      "requestID": "249f1ffd-613a-4c3d-a720-ed133ab5cc8c",
      "eventType": "AwsApiCall",
      "managementEvent": true,
      "eventCategory": "Management"
    }
  ]
}
```

Parsing of this record should return 2 records 

### Proposed solution

If VRL returns an array then that should be treated as multiple records.

```ruby
. = .Records
```

### Alternatives considered

none.

**Comment by hengfeiyang** [comment]
We should check the return is `Array` or `Object`

**Comment by sumeetattree** [comment]
Hey guys, I have a potential solution but I have a few questions:

1. Is there a switch/flag that decides if the value that is passed to the [`apply_stream_functions`](https://github.com/openobserve/openobserve/blob/main/src/service/ingestion/mod.rs#L356) is unflattened or flattened?
  a. If yes, who will pass this flag? The caller of the API?
  b. If no, then how do you decide when to flatten and when not to flatten?
2. I can see that before passing the data to the `apply_stream_functions`, it is being flattened [everywhere](https://github.com/openobserve/openobserve/blob/main/src/service/logs/syslog.rs#L135). What is the need for this pre-flattening if it is also [being flattened before returning](https://github.com/openobserve/openobserve/blob/ae6be3343857c77ff6581a0ce78252adb7911860/src/service/ingestion/mod.rs#L371) from the `apply_stream_functions`?
3. If an array is returned from [`apply_vrl_fn`](https://github.com/openobserve/openobserve/blob/main/src/service/ingestion/mod.rs#L368) do we need to distinguish between an array of objects `[ { ... }, { ... } ]` and a simple list `[...]`? Are both kinds of arrays considered as Records?
  Since there could be multiple stream functions left to apply to a value, will the subsequent functions apply to:
  a. Each array element individually? Or,
  b. The whole array?
4. After the application of all the stream functions, should [`flatten_with_level`](https://github.com/openobserve/openobserve/blob/main/src/config/src/utils/flatten.rs#L34) apply to the individual elements of the array (in case it is an array of objects) as well?

**Comment by oasisk** [comment]
@sumeetattree please find responses below:
Is there a switch/flag that decides if the value that is passed to the [apply_stream_functions](https://github.com/openobserve/openobserve/blob/main/src/service/ingestion/mod.rs#L356) is unflattened or flattened?
a. If yes, who will pass this flag? The caller of the API?
b. If no, then how do you decide when to flatten and when not to flatten?
_[Ashish] : We make sure before applying vrl function data is always flattened_

I can see that before passing the data to the apply_stream_functions, it is being flattened [everywhere](https://github.com/openobserve/openobserve/blob/main/src/service/logs/syslog.rs#L135). What is the need for this pre-flattening if it is also [being flattened before returning]
(https://github.com/openobserve/openobserve/blob/ae6be3343857c77ff6581a0ce78252adb7911860/src/service/ingestion/mod.rs#L371) from the apply_stream_functions?
_[Ashish] : Openobserve stores data in flatenned format , vrl function may result in non-flattened data , hence after applying vrl function , we flatten data again_

If an array is returned from [apply_vrl_fn](https://github.com/openobserve/openobserve/blob/main/src/service/ingestion/mod.rs#L368) do we need to distinguish between an array of objects [ { ... }, { ... } ] and a simple list [...]? Are both kinds of arrays considered as Records?
_[Ashish] : Can be both , 1st priority should be a simple list_

Since there could be multiple stream functions left to apply to a value, will the subsequent functions apply to:
a. Each array element individually? Or,
b. The whole array?  - 
_[Ashish] : To whole array_

After the application of all the stream functions, should [flatten_with_level](https://github.com/openobserve/openobserve/blob/main/src/config/src/utils/flatten.rs#L34) apply to the individual elements of the array (in case it is an array of objects) as well?
 _[Ashish] : this is already being done_

**Comment by sumeetattree** [comment]
Hey @oasisk thanks for your response.

I still have doubts:
1. Pre-flattening seems to be counter to the problem described in this issue. If the data is flattened before passing to the vrl_function, you would get something like this:
    ```json
    {
      "Records": "[{\"eventVersion\": \"1.08\",...}]"
    }
    ```
    If the end-user has to work with this object, then it becomes their responsibility to `parse_json!()` first. Is this the intended behavior?

2. I understand that OpenObserve is storing them as flattened objects, but that can happen right before the last step. These are the broad steps that I have understood a piece of data goes through:
  a. Ingestion,
  b. Transform (Apply VRL functions),
  c. Write/Store
  Flattening seems to be necessary only after Step b. Depending on your answer from Step 1, we might have to skip the pre-flattening.

3. It seems counter intuitive to me that if an array of records is returned from a VRL function, then the subsequent VRL functions do not apply to these individual records - but I will start working with the assumption that it applies to the whole array.

4. Understood. In case we decide to skip the flattening after Step 2a, we might have to flatten individual elements of the resulting array.

**Comment by sumeetattree** [comment]
Another follow up question:
The way the statement is worded seems like there should be two `Record`s returned by processing this data. Does that mean that when an array of objects is returned, each object in the array should be bubbled up as two distinct records?

**Comment by oasisk** [comment]
@sumeetattree 
1. yes user will have to use parse_json!() first , let's assume that the end users will follow it. As part of your implementation tests , vrl function that you write should also use parse_json!().   
2. NA
3. Typically user would know in order in which function are applied , so for now lets assume function which returns multiple records will be last one to be executed.

The way the statement is worded seems like there should be two Records returned by processing this data. Does that mean that when an array of objects is returned, each object in the array should be bubbled up as two distinct records?
_[Ashish]: Yes , based on special syntax `. = .Records` , let these be processed as multiple records. Function apply_stream_functions returns value which can be array of records & should be handled by appropriate service applying the function. You can try this for `_json` endpoint for now._

**Comment by hengfeiyang** [comment]
already support
