### ISSUE TITLE
I have created a Python Wrapper / Library

### ISSUE THREAD

**Issue by JustinGuese** [openobserve/openobserve#1117]
### Describe the problem that you experienced

https://github.com/JustinGuese/python-openobserve

Can we link it somehow in the Docs? I think it would add a lot of benefit

### Enter the URL of the topic with the problem

https://github.com/JustinGuese/python-openobserve

### Describe what you were looking for in the documentation

A python wrapper / library for easy usage

**Comment by prabhatsharma** [comment]
@JustinGuese Thanks for this. We however would prefer to have something generated directly from OpenAPI definition, which allows for minimal effort and management of the SDKs in multiple languages. Check https://pypi.org/project/openapi-python-generator/ You could generate python SDK pretty quickly using this. We have been holding off on generating the SDKs for multiple languages due to the high rate of API additions and changes in the project. We will be releasing official SDKs soon.
