### ISSUE TITLE
OO output log support config to file

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#1191]
### Description

std in k8s has some performance problem. if throughput raise , k8s will rotate std log frequently.   
consider support log to file will be more flexible for collecting and rotate

### Proposed solution

same as description

### Alternatives considered

not yet

**Comment by prabhatsharma** [comment]
Not sure what you mean by this. The way things work in k8s is that k8s asks docker (or any other runtime) to run the container. The runtime then captures any logs from stdout of container and stores them in files on the host that is running the container. Typically this file location is `/var/log/containers/*.log` .  You will then typically have a log forwarder which will tail these files and send them to OpenObserve.

Here is a sample fluentibit daemonset configuration for the above approach:

```yaml
[INPUT]
    Name tail
    Path /var/log/containers/*.log
    multiline.parser docker, cri
    Tag kube.*
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On
```

**Comment by hengfeiyang** [comment]
@domyway In v0.5.3 you can set a new env:

```
ZO_LOG_FILE="log.txt"
```

**Comment by eltoddo** [comment]
For anyone else who stumbles their way here, the undocumented env variable above no longer works, but found these in the code: 

![Image](https://github.com/user-attachments/assets/41a6efe4-f4b2-45c0-b5e4-2475781df7f4)

Note that ZO_LOG_FILE_DIR and ZO_LOG_FILE_NAME_PREFIX are also undocumented, so I don't assume they're officially supported or maintained.

For what its worth, the reason I'm looking for this is that if you set up OO as a Windows service, STDOUT/STDERR will be discarded. The undocumented log redirection means I'll be able to debug OO if I need to. I can't virtualize/containerize the app due to special reconfiguration I needed to do with Windows' virtualization layer to allow some other nonsense to work.

**Comment by hengfeiyang** [comment]
We support this configure like you said, but we don't recommend user to do that, so we have no document for this.
