### ISSUE TITLE
需要侧边栏进行常驻, 不要进行伸缩 (The sidebar needs to be permanent, not stretchable)

### ISSUE THREAD

**Issue by cooting-cn** [openobserve/openobserve#1451]
### Description

左侧菜单界面, 每次都要进行细看, 无法做到丝滑流畅使用 
(translated - On the left menu interface, you have to take a closer look every time, which cannot be used smoothly and smoothly)

### Proposed solution

建议做成常驻,r如图
(translated - It is recommended to make it permanent, r as shown in the figure)
![3213c067ec320fd407f6a762a44034e](https://github.com/openobserve/openobserve/assets/131133433/bead5c5b-36a2-4b69-9e43-c2c3253423c8)
或者设置一个固定开关, 让用户选着是佛伸缩, 最好默认常驻
(translated- Or set a fixed switch to allow users to choose whether to zoom in or out. It is best to default to permanent)

### Alternatives considered

无
(translated - none)

**Comment by prabhatsharma** [comment]
Why?

**Comment by hengfeiyang** [comment]
@prabhatsharma Many users talk about this, they aren't familiar with our UI, and they want to fix the menu and learn the menu. Maybe after some days, they can fold the menu as default.

**Comment by thomasdba** [comment]
> Why?

because it make users not comfortable .  If I need to jump to logs , first move the mouse to the left ,wait the menu out ,and the click . two steps , if one step can solve it ,why need two steps ?

**Comment by prabhatsharma** [comment]
Following is our logic for not expanding the left menu:

User would need to bring the pointer to the left, irrespective of the approach to click on any menu.
There is no wait time for the menu to appear. There is no animation or any other kind of wait. In terms of effort, to click the menu item it is no more than the "forever open" menu.

Keeping the menu forever open will reduce the result area significantly. Even if we give the option to hide the menu, most people will never close it since most people stick with the defaults. This reduces the usefulness of the application by making it harder to see and interpret results.

**Comment by thomasdba** [comment]
as cannot point to the right place directly ,even the very short time for the menu out ,logically it is still two steps. it is not a big deal to reduce result area as we use pc ,but not mobile device.

**Comment by thomasdba** [comment]
some os like macos dock has similar feature like this to hid, but it is a option and not default . the current way is different from most other applications or products , so even you persist your dedign, it is better to consider users feedback ,at least give us an option.
