### ISSUE TITLE
Installation with dynamodb restarts when tables are created first time

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#1486]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When we start using dynamo db as meta store for first time, dynamo tables are created as part of init job, the same job checks if root user exists in db.

This makes app fail with /user key not found

### Please provide the version you discovered this bug in (check about page for version information)

```true
v: 0.5.2
```

**Comment by taimingl** [comment]
Hi @oasisk, this looks like a quick fix by handling the case where key `/user/` does not exist when querying db in `root_user_exists()` function instead of unwrapping directly. I played with it and referenced my forked branch here. Let me know what you think, especially if there's more to it, would love to hear any pointers or suggestions.

**Comment by oasisk** [comment]
@taimingl , thx a lot for suggested fix, it further fails with resource not found , working on fixing it.

**Comment by taimingl** [comment]
thanks for the insights @oasisk. I will look further as well and definitely follow along to see how you approach it.
