### ISSUE TITLE
Syslog ingestion message values are 'cut off'

### ISSUE THREAD

**Issue by miklinson** [openobserve/openobserve#1514]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

No

### Description

Hi all!

We've recently been evaluating OpenObserve internally and have really found it useful. However we've encountered a problem we haven't seen anyone else come across in the GitHub issues.
When we send larger messages via syslog ingestion, we notice sometimes the message values are 'cut off'. Looking over some samples, it seems to be around the 970ish character mark.

We tested this with both our own applications and the [syslog generator](https://openobserve.ai/docs/ingestion/logs/syslog/#start-generating-test-syslog-data) in the documentation and were able to replicate.
Here's some samples:
![image](https://github.com/openobserve/openobserve/assets/8554385/4b91033d-fb80-4c33-8012-e7893c24a578)
![image](https://github.com/openobserve/openobserve/assets/8554385/72d29d18-04c7-4b40-8cfe-8b8496cc5fd6)
![image](https://github.com/openobserve/openobserve/assets/8554385/256493d6-e6dc-48ac-afb9-bec97220a49c)

We've tcpdump-ed and can see the data getting across to the OpenObserve server in full. Is this a configuration or bug? I know some syslog servers support RFC3164, which limits length to 1024 bytes, which seems fairly close to what we're seeing.
Any help is appreciated, thanks!

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.5.2
Commit Hash: 7c95c24c9d8a6427eb833557897d7fabfc54012b
Build Date: 2023-09-12T05:02:22Z
OS: Linux x64
```

### Anything else?

We're using v0.5.2 but it doesn't have a version and commit hash in the dashboard page:

![image](https://github.com/openobserve/openobserve/assets/8554385/084d38b7-14da-42d0-9b47-38688557abb2)

**Comment by oasisk** [comment]
@miklinson 
We would Support max size in line with standard [IEEE 802.3](https://en.wikipedia.org/wiki/IEEE_802.3) , which limits 1500 bytes of payload , with this we can support 1472 bytes (1500 - 20 (IP header ) -8 (UDP header) ) for UDP & 1460 bytes(1500 - 20 (IP header ) -20 (TCP header) ) for TCP

JUMBO frames are ruled out because : For jumbo frames , frame size used by an end-to-end connection is typically limited by the lowest frame size in intermediate links ,not only sender & receiver has to enable jumbo frames but  all intermediate links will have to support it.
