### ISSUE TITLE
[OTLP-Metrics] About data structure processing of metrics

### ISSUE THREAD

**Issue by GhostBoyBoy** [openobserve/openobserve#1997]
### Which OpenObserve functionalities are relevant/related to the feature request?

metrics

### Description

Question 1: min and max are not processed when Histogram type is processed in the OTLP protocol.  For http interfaces, we need to care about the max value.  For exemplars, as a json store, it is difficult to parse this structure when configuring monitoring diagrams.
Problem 2: Monitoring, logs, and links are closely coordinated.  The attribute of the [exemplars] data field of the metric Histogram type in the metric contains [traceId].  Can it be used as a metric label?

### Proposed solution

I haven't decided yet

### Alternatives considered

none

**Comment by GhostBoyBoy** [comment]
![image](https://github.com/openobserve/openobserve/assets/38995810/532054e7-c687-437d-b614-5f25c24d41ea)

**Comment by hengfeiyang** [comment]
https://opentelemetry.io/docs/specs/otel/metrics/data-model/#histogram
https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/
https://www.timescale.com/blog/prometheus-vs-opentelemetry-metrics-a-complete-guide/

> We can see a histogram is created in OpenTelemetry, but one thing we can’t do is include minimum and maximum values (which OpenTelemetry supports, but Prometheus doesn’t).

So, as default we dropped `min` and `max` fields because that Prometheus doesn't support it.

But we also can consider add two more new metrics name, like we already have `_count`, `_sum`, `_bucket` for `Histgoram` data type, we also can add `_min` and `_max` streams. We need to discuss if it is valuable.

**Comment by GhostBoyBoy** [comment]
> https://opentelemetry.io/docs/specs/otel/metrics/data-model/#histogram https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/ https://www.timescale.com/blog/prometheus-vs-opentelemetry-metrics-a-complete-guide/
> 
> > We can see a histogram is created in OpenTelemetry, but one thing we can’t do is include minimum and maximum values (which OpenTelemetry supports, but Prometheus doesn’t).
> 
> So, as default we dropped `min` and `max` fields because that Prometheus doesn't support it.
> 
> But we also can consider add two more new metrics name, like we already have `_count`, `_sum`, `_bucket` for `Histgoram` data type, we also can add `_min` and `_max` streams. We need to discuss if it is valuable.

I agree that we should add _min and _max streams.
