### ISSUE TITLE
Query: Support join over multiple streams 

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#205]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

We support searching on single stream today.

### Proposed solution

Add support for querying multiple streams using joins 

### Alternatives considered

NA

**Comment by hengfeiyang** [comment]
What are the scenarios? can you give some examples?

I checked `open search` then support:

https://opensearch.org/docs/1.0/search-plugins/sql/index/#rest-api

```sql
select * from table limit 50
select * from table1,table2,table3 limit 50
select * from my-table-* limit 50
```

But, this is es syntax, all tables have some data fields.

**Comment by graemecurtis** [comment]
I think that this relates to SQL JOINS rather than simple table aggregation.

e.g.

SELECT p.device_name, p.url, p.user, d.is_domain_admin, d.manager, d.member_of
FROM proxy_steam p
JOIN directory_stream d
ON p.user = d.username

The open search equivalent would be: https://opensearch.org/docs/1.0/search-plugins/sql/complex/

Would recommend that joins are done as hash joins rather than merge joins in similar way to that used by datafusion (https://godatadriven.com/blog/making-joins-faster-in-datafusion-based-on-table-statistics/)

**Comment by ancoron** [comment]
I would like to calculate the percentage of memory used by a container or node in relation to its defined maximum (memory reservation limit for containers, total logical memory for nodes).

In PromQL, this is pretty easy (e.g. using container metrics as exposed by cAdvisor):
```promql
max by (name) (100 / container_spec_memory_limit_bytes * container_memory_usage_bytes)
```

In this case, the SQL would look like this:
```sql
SELECT
    histogram(metric_a._timestamp) as "x_axis_1",
    metric_a.name as "x_axis_2",
    max(100 / metric_a.value * metric_b.value) as "y_axis_1"
FROM "container_spec_memory_limit_bytes" AS metric_a
INNER JOIN "container_spec_memory_usage_bytes" AS metric_b ON (metric_a.name = metric_b.name)
GROUP BY x_axis_1, x_axis_2
ORDER BY x_axis_1 ASC
```
...however, it would require some more support for creating an actual 1-to-1 match for each histogram time bucket, so that the internal calculation doesn't explode in terms of rows to process.

Has datafusion support for something like this already?

**Comment by prabhatsharma** [comment]
test issue with mediafire

**Comment by hengfeiyang** [comment]
done
