### ISSUE TITLE
Federated Search for openobserve

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#2508]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

Federated search refers to the capability to search across multiple clusters as if they were a single entity. This approach is particularly useful when data is distributed across different clusters for various reasons like geographical distribution, organisational policies, or scalability concerns.

**This would be enterprise feature**

### Proposed solution

To use federated, user would have to configure remote clusters. This can be done using the Cluster API(to be introduced) , to which one would specify the remote clusters by specifying cluster urls & appropriate credentials for clusters.

Once remote clusters are set up, user can issue a cross cluster query by specifying streams to be searched from each of the cluster.

For instance, if you have two clusters, cluster_one and cluster_two, you can perform a search across both clusters by choosing a specific stream from each of them.

The query is executed in parallel across the specified streams on respective remote cluster, and the results are merged.

User would receive search results which are combined results from the different clusters. 

**Security Configuration**: We need to ensure that the user or API making the federated search request has the necessary permissions on all involved clusters

**Network Latency:** Queries might involve network calls between clusters, which could impact performance. Timeout for each cluster should be specified during cluster registration. This will allow for better SLA management when clusters are located across regions and cloud services.

**Consistent Mapping**: Ensure that streams in different clusters have fields which are being queried.

### Alternatives considered

NA

**Comment by Yadumathur** [comment]
Will design going two be two layers federated ?
Queriers --> Cluster API -->> Ingestors + Blob stores ?

How do we ensure the blob results + WAL results are managed and merged from different regions within a limited timewindow , because we may face different latencies for these systems and merging may Wait or die with timeouts.
Are we planning to window size the queries to only pull selective results in a single time frame. 
Pull first 1000 results per 1 min window and provide it to display , but run the complete count of results and display "matched result count" ?
In case of further drill down , a new query can be launched for that time frame.
