### ISSUE TITLE
No log filtering examples (if log filtering even is possible)

### ISSUE THREAD

**Issue by notnarb** [openobserve/openobserve#2602]
### Describe the problem that you experienced

Reading through https://openobserve.ai/blog/filter-logs-at-source-in-otel-collector/ I see:

> Also if you are using OpenObserve, you can use [functions](https://openobserve.ai/docs/user-guide/functions/) to filter logs, metrics and traces in OpenObserve itself before it is stored.

However searching that linked page, the word "filter" is not mentioned.

My interpretation of the word "filter" here leads me to believe I can *drop logs in their entirety* -- perhaps that is a flawed assumption on my part.

---

Looking through the Vector docs I see examples of how to filter events: https://vector.dev/docs/reference/vrl/#example-filtering-events, but that seems to be tied to a specific "condition" configuration but I see nothing of the sort in the OpenObserve documentation.

### Enter the URL of the topic with the problem

https://openobserve.ai/docs/user-guide/functions/

### Describe what you were looking for in the documentation

Either:

1) A brief example of how to drop a log or

2) An explicit statement that OpenObserve functions only support 1:1 transformations of logs (e.g. adding or transforming a field).

### Provide any additional information here in as much as detail as you can

```true
Version: v0.7.2
Commit Hash: c6e7b19b28e948cfc65e4dfb3d26a0cfebbec3f8
Build Date: 2023-11-30T07:28:47Z
```

**Comment by gorec2005** [comment]
Hi!
may be anyone explain how i can add src-ip for log message in vrl - may be it's impossible?
(hostname in syslog message is absent :-()

**Comment by prabhatsharma** [comment]
@notnarb Totally missed this one. We had the filtering capability earlier, but we had to remove it as there are very few users using the filtering capability. By default you had to add a dot `.` at the end to accept the transformed record. If you did not put `.` at the end then we would not return anything. Since people were new to VRL almost all users would not put `.` at the end and would face an issue and most of them did not want to filter the records. Hence we removed the mechanism for now. We will think of a better UX for this.

**Comment by prabhatsharma** [comment]
> may be anyone explain how i can add src-ip for log message in vrl - may be it's impossible?
(hostname in syslog message is absent :-()

Can you provide some more detail?

**Comment by gorec2005** [comment]
Some hardware(dlink DGS1210-52) send syslog without hostname at all :-( :

{"_timestamp":1707624471000000,"facility":"local3","message":"Port 8 link up, 1Gbps FULL duplex","severity":"info"}
{"_timestamp":1707557843000000,"appname":"","facility":"local0","hostname":"10.10.10.3","message":"Port 14 link down","procid":"LinkStatus","severity":"info"}

how i can with VRL or some else  reconstruct message for add src-ip (from which this log event got)?

may be like this in functions->stream association->:
```
.host = %src-ip
.
```

**Comment by gorec2005** [comment]
or may be possible do more than one listen port for syslog? and tag it with internal tag like organization...

**Comment by prabhatsharma** [comment]
@gorec2005 
You could write something like:

```ruby
if .src_ip == null {
.src_ip = "192.168.1.1"
}
```

https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiaWYgLnNyY19pcCA9PSBudWxsIHtcbi5zcmNfaXAgPSBcIjE5Mi4xNjguMS4xXCJcbn0iLCJldmVudCI6eyJtZXNzYWdlIjoiSGVsbG8gVlJMIiwiZm9vIjoiZGVsZXRlIG1lIiwiaHR0cF9zdGF0dXMiOiIyMDAifSwiaXNfanNvbmwiOmZhbHNlLCJlcnJvciI6bnVsbH0%3D

**Comment by Rajin9601** [comment]
>Since people were new to VRL almost all users would not put . at the end and would face an issue and most of them did not want to filter the records. Hence we removed the mechanism for now. We will think of a better UX for this.

I want to suggest the `abort` keyword for filtering UX. 
In vector, they have `drop_on_abort` config which drops the record when remapping function aborts explicitly.
https://vector.dev/docs/reference/configuration/transforms/remap/#drop_on_abort
https://vector.dev/highlights/2021-04-21-vrl-abort/

It would be great to have option of dropping the record in VRL, because it would allow user to filter the records based on the parsed values.
