### ISSUE TITLE
Amazon SNS as an alert destination

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#4136]
### Which OpenObserve functionalities are relevant/related to the feature request?

alerts

### Description

Amazon SNS can be a good target that is used by a lot of people for sending notifications. This can be used for a lot of use cases.

### Proposed solution

Support Amazon SNS as a destination

### Alternatives considered

NA

**Comment by CuriousCorrelation** [comment]
Thanks @oasisk for assigning me this issue. It's an interesting challenge!

Let me describe the issue just so I can align my approach:

The idea is to integrate Amazon SNS support into the alert destination system. After going over the codebase, I think much of the plumbing is already there, we just need to integrate by following SNS docs.

I have a couple of approaches in mind, one that is quite straightforward and requires minimal refactor, and one that can simplify the process and perhaps improve DX for future integrations, but there are a couple of hard blockers in the way right now so the later approach will need to be paired with a phased approach. In both cases we’ll begin with this:

Let’s start with my very rough draft just so I can get a better understanding of the codebase and invite feedback.

We'll extend the existing `Destination` struct to include SNS-specific fields (like topic ARN and region) rather than creating a separate enum variant (part of the phased approach).

We'll need to update our alert logic, maybe add new API endpoints for SNS destination management (I don’t think this is required, just mentioning for ref), and implement SNS-specific sending logic using the AWS SDK for Rust.

I also plan to add comprehensive test coverage for this new feature after I’m sure the approach is solid. I'd appreciate any thoughts or concerns about this approach before I dive into the implementation details.

# Plan

## 1. Refactor Destination Type

Instead of completely replacing the existing `Destination` struct with an enum, we'll extend it to include SNS-specific fields. This approach maintains backward compatibility.

```rust
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct Destination {
	pub name: String,
	pub url: String,
	pub method: HTTPType,
	pub skip_tls_verify: bool,
	pub headers: Option<HashMap<String, String>>,
	pub template: String,
	pub emails: Vec<String>,
	pub destination_type: DestinationType,
	// New SNS-specific fields
	#[serde(skip_serializing_if = "Option::is_none")]
	pub sns_topic_arn: Option<String>,
	#[serde(skip_serializing_if = "Option::is_none")]
	pub aws_region: Option<String>,
}

#[derive(Serialize, Debug, Default, PartialEq, Eq, Deserialize, Clone, ToSchema)]
pub enum DestinationType {
	#[default]
	#[serde(rename = "http")]
	Http,
	#[serde(rename = "email")]
	Email,
	#[serde(rename = "sns")]
	SNS,
}
```

## 2. Update Destination-related Functions

Modify the `save`, `get`, `list`, and `delete` functions in the destinations service to handle the new SNS type:

Here’s an example of the new save function from https://github.com/openobserve/openobserve/blob/8a8c11a771e4a053e8df373b2fdb522675fc39d9/src/service/alerts/destinations.rs#L30

```rust
pub async fn save(org_id: &str, name: &str, mut destination: Destination, create: bool) -> Result<(), (http::StatusCode, anyhow::Error)> {
	match destination.destination_type {
    	DestinationType::Http => {
        	if destination.url.is_empty() {
            	return Err((http::StatusCode::BAD_REQUEST, anyhow::anyhow!("URL is required for HTTP destinations")));
        	}
    	}
    	DestinationType::Email => {
        	if destination.emails.is_empty() {
            	return Err((http::StatusCode::BAD_REQUEST, anyhow::anyhow!("At least one email is required for Email destinations")));
        	}
    	}
    	DestinationType::SNS => {
        	if destination.sns_topic_arn.is_none() || destination.aws_region.is_none() {
            	return Err((http::StatusCode::BAD_REQUEST, anyhow::anyhow!("Topic ARN and Region are required for SNS destinations")));
        	}
    	}
	}

	// Rest of the save logic...
}
```

## 3. Implement SNS Alert Sending Functionality

Add a new function to handle sending alerts via SNS:

Similar to https://github.com/openobserve/openobserve/blob/8a8c11a771e4a053e8df373b2fdb522675fc39d9/src/service/alerts/alert.rs#L455

```rust
async fn send_sns_alert(topic_arn: &str, region: &str, message: &str) -> Result<(), Box<dyn std::error::Error>> {
	let config = aws_config::defaults(aws_config::BehaviorVersion::latest())
    	.region(aws_config::Region::new(
        	dest.aws_region.clone().unwrap_or_default(),
    	))
    	.load()
    	.await;
	let client = aws_sdk_sns::Client::new(&config);

	client
    	.publish()
    	.topic_arn(topic_arn)
    	.message(message)
    	.send()
    	.await?;

	Ok(())
}
```

## 4. Update API Handlers

Modify the handlers in `http/request/alerts/destination.rs` to handle the new SNS destination type. Unsure right now.

## 5. Modify Integration Tests

Add new tests for SNS destinations and update existing tests where necessary. The tests would look something along the lines of

```rust
async fn e2e_post_sns_alert_destination() {
	let auth = setup();
	let body_str = r#"{
    	"name": "sns_alert",
    	"destination_type": "sns",
    	"sns_topic_arn": "arn:aws:sns:us-east-1:123456789012:MyTopic",
    	"aws_region": "us-east-1",
    	"template": "snsTemplate"
	}"#;
	// ... rest of the test implementation
}
```

The we add this to the e2e_test function:
```
e2e_post_sns_alert_destination().await;
```

Update other relevant tests like `e2e_get_alert_destination`, `e2e_list_alert_destinations`, and `e2e_delete_alert_destination` to handle SNS destinations from https://github.com/openobserve/openobserve/blob/main/tests/integration_test.rs

**Comment by oasisk** [comment]
@CuriousCorrelation LGTM , please can you please raise a PR for same.

**Comment by CuriousCorrelation** [comment]
Thank you @oasisk PR is up at https://github.com/openobserve/openobserve/pull/4247
